const PageContent = require('../models/PageContent');
const LibraryArticle = require('../models/LibraryArticle');

// ─── Page Content (CMS) ───
const getPageContent = async (req, res) => {
  try {
    const content = await PageContent.findOne({ page: req.params.page });
    if (content) res.json(content);
    else res.status(404).json({ message: 'Page content not found' });
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

const updatePageContent = async (req, res) => {
  const { sections } = req.body;
  try {
    let content = await PageContent.findOne({ page: req.params.page });
    if (content) {
      content.sections = sections;
      await content.save();
      res.json(content);
    } else {
      content = await PageContent.create({ page: req.params.page, sections });
      res.status(201).json(content);
    }
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

// ─── Content Library (Articles) ───

// GET /api/content/library
const getLibraryArticles = async (req, res) => {
  try {
    const articles = await LibraryArticle.find({ user: req.user._id }).sort({ createdAt: -1 });
    res.json(articles);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching articles', error: error.message });
  }
};

// POST /api/content/library
const saveLibraryArticle = async (req, res) => {
  try {
    if (!req.user || !req.user._id) {
      return res.status(401).json({ message: 'Unauthorized', error: 'User context is missing' });
    }

    const { title, content, seoScore, readabilityScore, words, ...rest } = req.body;
    
    if (!title) {
      return res.status(400).json({ message: 'Validation Error', error: 'Article title is required' });
    }

    const safeNum = (val) => {
      // Extract numbers if string contains text (e.g. "800 words" -> 800)
      if (typeof val === 'string') {
        const match = val.match(/\d+/);
        if (match) return Number(match[0]);
      }
      const num = Number(val);
      return isNaN(num) ? null : num;
    };

    const article = await LibraryArticle.create({
      ...rest,
      title: title,
      content: content || 'No content was generated by the AI for this article.',
      seoScore: safeNum(seoScore),
      readabilityScore: safeNum(readabilityScore),
      words: safeNum(words) || 0,
      user: req.user._id
    });
    res.status(201).json(article);
  } catch (error) {
    res.status(500).json({ message: 'Error saving article', error: error.message });
  }
};

// DELETE /api/content/library/:id
const deleteLibraryArticle = async (req, res) => {
  try {
    const article = await LibraryArticle.findOneAndDelete({ 
      _id: req.params.id, 
      user: req.user._id 
    });
    if (!article) return res.status(404).json({ message: 'Article not found' });
    res.json({ message: 'Article deleted' });
  } catch (error) {
    res.status(500).json({ message: 'Error deleting article', error: error.message });
  }
};

module.exports = { 
  getPageContent, 
  updatePageContent,
  getLibraryArticles,
  saveLibraryArticle,
  deleteLibraryArticle
};
